version: 1.0
provider:
  name: openfaas
  gateway: https://veba.lab.core.pilue.co.uk
functions:
  veba-echo:
    lang: python3-http
    handler: ./echo
    image: vmware/veba-python-echo:latest
    environment:
      write_debug: true
      read_debug: true
    annotations:
<<<<<<< HEAD
      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent,VmPoweredOffEvent"
=======
      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent,VmPoweredOffEvent,DvsPortLinkUpEvent,DatastoreRenamedEvent,DVPortgroupRenamedEvent,ResourcePoolCreatedEvent,DatastoreFileCopiedEvent"
>>>>>>> Removed old powershell attempts
