version: 1.0
provider:
  name: openfaas
  gateway: https://VEBA_FQDN_OR_IP
functions:
  python-vro:
    lang: python3
    handler: ./vro
    image: pilue/veba-python-vro:latest
    environment:
      write_debug: true
      read_debug: true
      insecure_ssl: true
      vro_workflow_id: "VRO_WORKFLOW_ID"
    secrets:
      - vroconfig
    annotations:
      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent,VmPoweredOffEvent"
